name: Build OVA

on:
  workflow_dispatch:

jobs:
  build-ova:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up dependencies
      run: |
        sudo apt update
        sudo apt install -y packer qemu-kvm libvirt-daemon-system libvirt-clients genisoimage
        
    - name: Install Packer QEMU Plugin
      run: |
        packer plugins install github.com/hashicorp/qemu
        
    - name: Validate Packer template
      run: |
        packer validate packer/arch-template.pkr.hcl

    - name: Build OVA
      run: |
        packer init packer/arch-template.pkr.hcl
        packer build packer/arch-template.pkr.hcl

    - name: Upload OVA artifact
      uses: actions/upload-artifact@v3
      with:
        name: arch-linux.ova
        path: output/arch-linux.ova
